exports.Reset = '\x1B[0m'
exports.Bright = '\x1B[1m'
exports.Dim = '\x1B[2m'
exports.Underscore = '\x1B[4m'
exports.Blink = '\x1B[5m'
exports.Reverse = '\x1B[7m'
exports.Hidden = '\x1B[8m'

exports.FgBlack = '\x1B[30m'
exports.FgRed = '\x1B[31m'
exports.FgGreen = '\x1B[32m'
exports.FgYellow = '\x1B[33m'
exports.FgBlue = '\x1B[34m'
exports.FgMagenta = '\x1B[35m'
exports.FgCyan = '\x1B[36m'
exports.FgWhite = '\x1B[37m'

exports.BgBlack = '\x1B[40m'
exports.BgRed = '\x1B[41m'
exports.BgGreen = '\x1B[42m'
exports.BgYellow = '\x1B[43m'
exports.BgBlue = '\x1B[44m'
exports.BgMagenta = '\x1B[45m'
exports.BgCyan = '\x1B[46m'
exports.BgWhite = '\x1B[47m'

exports.rover = '\x1B[32m'
exports.base = '\x1B[36m'
